# Default VIA settings
VIA_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no

# Added settings
TAP_DANCE_ENABLE = yes
BOOTMAGIC_ENABLE = full
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812